<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25842" started-at="2021-11-04T11:33:03 SAST" finished-at="2021-11-04T11:33:28 SAST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25842" started-at="2021-11-04T11:33:03 SAST" finished-at="2021-11-04T11:33:28 SAST">
      <class name="runner.ProductRunner">
        <test-method status="FAIL" signature="TC_ProductRules1To9()[pri:2, instance:runner.ProductRunner@4de4b452]" name="TC_ProductRules1To9" duration-ms="25457" started-at="2021-11-04T11:33:03 SAST" finished-at="2021-11-04T11:33:28 SAST">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONArray[2] not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONArray[2] not found.
at org.json.JSONArray.get(JSONArray.java:264)
at org.json.JSONArray.getJSONObject(JSONArray.java:477)
at com.exergyRestApi.Product.productRules.ProductRuleTestCases.Tc1ToTC9(ProductRuleTestCases.java:69)
at runner.ProductRunner.TC_ProductRules1To9(ProductRunner.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_ProductRules1To9 -->
        <test-method status="PASS" signature="EndTests()[pri:0, instance:runner.ProductRunner@4de4b452]" name="EndTests" is-config="true" duration-ms="320" started-at="2021-11-04T11:33:28 SAST" finished-at="2021-11-04T11:33:28 SAST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EndTests -->
      </class> <!-- runner.ProductRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
