<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="5" total="6" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-11-16T10:43:48 SAST" name="Default suite" finished-at="2021-11-16T10:43:54 SAST" duration-ms="6838">
    <groups>
    </groups>
    <test started-at="2021-11-16T10:43:48 SAST" name="Default test" finished-at="2021-11-16T10:43:54 SAST" duration-ms="6838">
      <class name="runner.ProductRunner">
        <test-method signature="Product_1960C_Rates()[pri:6, instance:runner.ProductRunner@4f704591]" started-at="2021-11-16T10:43:48 SAST" name="Product_1960C_Rates" finished-at="2021-11-16T10:43:54 SAST" duration-ms="6391" status="FAIL">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONArray[0] not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONArray[0] not found.
at org.json.JSONArray.get(JSONArray.java:264)
at org.json.JSONArray.getJSONObject(JSONArray.java:477)
at com.exergyRestApi.Product.Rates.Product_1960C_TestCases.Product_1960C(Product_1960C_TestCases.java:215)
at runner.ProductRunner.Product_1960C_Rates(ProductRunner.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Product_1960C_Rates -->
        <test-method is-config="true" signature="EndTests()[pri:0, instance:runner.ProductRunner@4f704591]" started-at="2021-11-16T10:43:54 SAST" name="EndTests" finished-at="2021-11-16T10:43:54 SAST" duration-ms="403" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EndTests -->
      </class> <!-- runner.ProductRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
