<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Tokyos-Air" failures="0" tests="4" name="runner.ProductRunner" time="1.156" errors="1" timestamp="2021-11-12T05:07:23 SAST" skipped="3">
  <testcase classname="runner.ProductRunner" name="Product_1960C_Rates" time="1.156">
    <error message="partnerPremiumAmount25K field is not found" type="com.codoid.products.exception.FilloException">
      <![CDATA[com.codoid.products.exception.FilloException: partnerPremiumAmount25K field is not found
at com.codoid.products.fillo.Recordset.getField(Recordset.java:163)
at com.exergyRestApi.Repo.Product.ProductsRateRepo.loadTCExpectedResponseFor1960(ProductsRateRepo.java:130)
at com.exergyRestApi.Product.Rates.Product_1960E_TestCases.Product_1960E(Product_1960E_TestCases.java:48)
at runner.ProductRunner.Product_1960C_Rates(ProductRunner.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Product_1960C_Rates -->
  <system-out/>
  <testcase classname="runner.ProductRunner" name="TC_ProductRules">
    <skipped/>
  </testcase> <!-- TC_ProductRules -->
  <system-out/>
  <testcase classname="runner.ProductRunner" name="Product_60200000_Rates">
    <skipped/>
  </testcase> <!-- Product_60200000_Rates -->
  <system-out/>
  <testcase classname="runner.ProductRunner" name="Product_60100000_Rates">
    <skipped/>
  </testcase> <!-- Product_60100000_Rates -->
  <system-out/>
</testsuite> <!-- runner.ProductRunner -->
